# Make sure to allocate enough memory in Docker.  This configuration 
# has 3 nodes and each has a mem_limit of 1g so that's already 3 gigs.

# Exposed ports
# 9200: Elasticsearch HTTP
# 9300: Elasticsearch TCP transport
# 5601: Kibana

# Nodes:
#   es-master: master
#   es-1
#   es-2
#   kibana-1

version: '2'
services:
  es-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: es-master
    environment:
      - node.name=es-master
      - cluster.name=docker-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch-net

  es-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: es-1
    environment:
      - node.name=es-1
      - cluster.name=docker-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata-2:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net

  es-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: es-2
    environment:
      - node.name=es-2
      - cluster.name=docker-elasticsearch-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata-3:/usr/share/elasticsearch/data
    networks:
      - elasticsearch-net

  kibana-1:
    image: docker.elastic.co/kibana/kibana:5.3.2
    container_name: kibana-1
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      SERVER_NAME: kibana-1
      ELASTICSEARCH_URL: http://es-master:9200/      
    depends_on:
      - es-master
    ports:
      - 5601:5601
    networks:
      - elasticsearch-net

volumes:
  esdata-1:
    driver: local
  esdata-2:
    driver: local
  esdata-3:
    driver: local

networks:
  elasticsearch-net:
    driver: bridge
